export default {
  logo: {
    logo: require('../assets/images/logo/logo_bg1.png'),
  },
  allarest_pro_bg: {
    full_bg: require('../assets/images/backgrounds/bg.png')
  },
  form_bg: {
    form_bg: require('../assets/images/backgrounds/formbg.png'),
  },
  allarest_jobs: {
    jobs_bg: require('../assets/images/backgrounds/jobsbg.png')
  },
  profile_screen: {
    default_avatar: require('../assets/images/default-avatar.png'),
    default_male_profile_photo: require('../assets/images/default_profile_male.jpg'),
    default_female_profile_photo: require('../assets/images/female_default_profile_photo.jpg'),
  },
  icons: {
    carIcon: require('../assets/images/icons/car.png'),
    shareIconWhite: require('../assets/images/icons/shareWhite.png'),
    editIcon: require('../assets/images/icons/edit.png'),
    tickIcon: require('../assets/images/icons/tick.png'),
    addjobIocn: require('../assets/images/icons/add-job.png'),
    backIcon: require('../assets/images/icons/back-icon.png'),
    completeIcon: require('../assets/images/icons/complete.png'),
    billingIcon: require('../assets/images/icons/billing.png'),
    billingPaypal: require('../assets/images/icons/billing-paypal.png'),
    cardnumIcon: require('../assets/images/icons/card-num.png'),
    cameraIcon: require('../assets/images/icons/camera.png'),
    msgReceiveIcon: require('../assets/images/icons/message-receive.png'),
    msgSentIcon: require('../assets/images/icons/message-sent.png'),
    addIcon: require('../assets/images/icons/add.png'),
    jobsIcon: require('../assets/images/icons/jobs.png'),
    messagesIcon: require('../assets/images/icons/messages.png'),
    favoritesIcon: require('../assets/images/icons/favorites.png'),
    agentIcon: require('../assets/images/icons/agents.png'),
    earningsIcon: require('../assets/images/icons/earnings.png'),
    settingsIcon: require('../assets/images/icons/settings.png'),
    aboutIcon: require('../assets/images/icons/about.png'),
    logoutIcon: require('../assets/images/icons/logout.png'),
    shareIcon: require('../assets/images/icons/shareIcon.png'),
    msgProfileIcon: require('../assets/images/icons/msgprofile.png'),
    dropDown: require('../assets/images/icons/dropdown.png'),
    dropup: require('../assets/images/icons/dropup.png'),
    heartIcon: require('../assets/images/icons/heart.png'),
    filtersIcon: require('../assets/images/icons/filters.png'),
    sendIcon: require('../assets/images/icons/send.png'),
    searchIcon: require('../assets/images/icons/search.png'),
    leftArrowIcon: require('../assets/images/icons/left-arrow.png'),
    qualityIcon: require('../assets/images/icons/quality.png'),
    Warning: require('../assets/images/icons/Warning.png'),
    qualityHighIcon: require('../assets/images/icons/quality-high.png'),
    calendarIcon: require('../assets/images/icons/calendar.png'),
    clockIcon: require('../assets/images/icons/clock.png'),
    mapIcon: require('../assets/images/icons/map.png'),
    starIcon: require('../assets/images/icons/star.png'),
    leftArrowWhiteIcon: require('../assets/images/icons/left-arrow-white.png'),
    minusIcon: require('../assets/images/icons/minus.png'),
    plusIcon:  require('../assets/images/icons/plus.png'),
    closeIcon: require('../assets/images/icons/close.png'),
    delete: require('../assets/images/icons/delete.png'),
    closeWhiteIcon: require('../assets/images/icons/close-icon.png'),
    instagramIcon: require('../assets/images/icons/instagram.png'),
    youtubeIcon: require('../assets/images/icons/youtube.png'),
    facebookIcon: require('../assets/images/icons/facebook.png'),
    certifiedIcon: require('../assets/images/icons/certified.png'),
    supportIcon: require('../assets/images/icons/support.png'),
    notificationIcon: require('../assets/images/icons/notification-bell.png'),
    blackFacouriteIcon: require('../assets/images/icons/noun_Heart.png'),
    tourIcon: require('../assets/images/icons/tour.png'),
    messageIcon: require('../assets/images/icons/message.png'),
    paymentIcon: require('../assets/images/icons/payment.png'),
    rightArrowIcon: require('../assets/images/icons/right-arrow.png'),
    favoriteIcon: require('../assets/images/icons/favoriteIcon.png'),
    contactIcon: require('../assets/images/icons/contact.png'),
    notification: require('../assets/images/icons/notification.png'),
  },
  launch_screen: {
    launch1: require('../assets/images/backgrounds/launch1.png'),
    launch2: require('../assets/images/backgrounds/launch2.png'),
    launch3: require('../assets/images/backgrounds/launch3.png')
  },
  backgrounds: {
    launchBg: require('../assets/images/backgrounds/bgOver.png')
  },
  tourImages: {
    tourImage_one: require('../assets/images/tour-images/tourImage1.png'),
    tourImage_two: require('../assets/images/tour-images/tourImage2.png'),
    tourImage_three: require('../assets/images/tour-images/tourImage3.png'),
    tourImage_four: require('../assets/images/tour-images/tourImage4.png'),
    tourImage_five: require('../assets/images/tour-images/tourImage5.png'),
    natureImage: require('../assets/images/tour-images/nature.jpg'),
    sightSeeing: require('../assets/images/tour-images/sight-seeing.png'),
    food: require('../assets/images/tour-images/food.png'), 
    nightLife: require('../assets/images/tour-images/night-life.png'),
    adventure: require('../assets/images/tour-images/adventure.png'),
    local: require('../assets/images/tour-images/local.png'),
    sports: require('../assets/images/tour-images/sports.png'),
  }
};
